server:
  port: 81

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pd_store?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  rabbitmq:
    host: 192.168.64.140   # wht6.cn
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual

  elasticsearch:
    rest:
      uris: http://192.168.64.150:9200

mybatis:
  mapperLocations: classpath:com.pd.mapper/*.xml

logging:
  level:
    cn.tedu.ssm.mapper: debug
    tracer: TRACE
resources: # 指定静态资源的路径
  static-locations: classpath:/
  cache-period: 0

